server:
  port: 8089

spring:
  application:
    name: Subject-Service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db
    username: root
    password: Vivan@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
    com.college: DEBUG
  file:
    name: logs/subject-service.log
    max-size: 10MB
    max-history: 30